ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -16,9 +16,9 @@ jobs:
         run: go version
       - name: go fmt
         run: files=$(gofmt -l .); if [[ -n "$files" ]]; then echo -e "::error::go fmt failed\n$files"; exit 1; fi
+      - name: go test
+        run: go test ./...
       - name: go imports
         run: |
           go install golang.org/x/tools/cmd/goimports@latest
-          files=$(goimports -l .); if [[ -n "$files" ]]; then echo -e "::error::go imports failed\n$files"; fi
-      - name: go test
-        run: go test ./...
+          files=$(goimports -l .); if [[ -n "$files" ]]; then echo -e "::error::go imports failed\n$files"; exit 1; fi
